FROM alpine:3.14
LABEL org.opencontainers.image.source=https://github.com/vlaurin/action-ghcr-prune
LABEL org.opencontainers.image.description="Stub Docker image used for automated testing of vlaurin/action-ghcr-prune."
ENTRYPOINT ["echo", "test:007"]
