name: 'GHCR Pruning'
description: 'GitHub Action to prune/delete container versions from GitHub Container Registry (ghcr.io)'
branding:
  icon: 'scissors'
  color: 'blue'
inputs:
  token:
    description: 'Secret access token with scopes `packages:read` and `packages:delete` and write permissions on the targeted container'
    required: true
  organization:
    description: 'Organisation to which the container belongs'
    required: false
  user:
    description: 'User to which the container belongs'
    required: false
  container:
    description: 'Name of the container to prune'
    required: true
  dry-run:
    description: 'When `true` prints out matching container versions without pruning them'
    required: false
    default: false
  older-than:
    description: 'Minimum age in days of container versions to prune'
    required: false
    default: 0
  keep-last:
    description: 'Count of most recent, matching containers to exclude from pruning'
    required: false
    default: 0
  untagged:
    description: 'Whether untagged container versions should be pruned'
    required: false
    default: false
  tag-regex:
    description: 'Regular expression matching tagged container versions which should be pruned'
    required: false
output:
  count:
    description: 'Count of container versions that were pruned'
runs:
  using: 'node12'
  main: 'index.js'
